const SelectionDatas = [
        { id: 1, selectionData: 'JavaScript (Node.js)' },
        { id: 2, selectionData: 'React' },
        { id: 3, selectionData: 'Express.js' },
        { id: 4, selectionData: 'Axios' },
        { id: 5, selectionData: 'Lodash' },
        { id: 6, selectionData: 'Moment.js' },
        { id: 7, selectionData: 'Python' },
        { id: 8, selectionData: 'Flask' },
        { id: 9, selectionData: 'Django' },
        { id: 10, selectionData: 'Requests' },
        { id: 11, selectionData: 'Pandas' },
        { id: 12, selectionData: 'NumPy' },
        // { id: 13, selectionData: 'PHP' },
        // { id: 14, selectionData: 'Laravel' },
        // { id: 15, selectionData: 'Guzzle' },
        // { id: 16, selectionData: 'Symfony' },
        // { id: 17, selectionData: 'Monolog' },
        // { id: 18, selectionData: 'PHPUnit' },
        // { id: 19, selectionData: 'Ruby' },
        // { id: 20, selectionData: 'Rails' },
        // { id: 21, selectionData: 'Devise' },
        // { id: 22, selectionData: 'Pundit' },
        // { id: 23, selectionData: 'RSpec' },
        // { id: 24, selectionData: 'Sinatra' },
        // { id: 25, selectionData: 'Java' },
        // { id: 26, selectionData: 'Spring Boot' },
        // { id: 27, selectionData: 'Hibernate' },
        // { id: 28, selectionData: 'JUnit' },
        // { id: 29, selectionData: 'Apache Commons' },
        // { id: 30, selectionData: 'Log4j' },
        // { id: 31, selectionData: 'C# (.NET)' },
        // { id: 32, selectionData: 'Entity Framework' },
        // { id: 33, selectionData: 'NUnit' },
        // { id: 34, selectionData: 'AutoMapper' },
        // { id: 35, selectionData: 'Dapper' },
        // { id: 36, selectionData: 'Serilog' },
        // { id: 37, selectionData: 'Go' },
        // { id: 38, selectionData: 'Gin' },
        // { id: 39, selectionData: 'Gorm' },
        // { id: 40, selectionData: 'Viper' },
        // { id: 41, selectionData: 'Cobra' },
        // { id: 42, selectionData: 'Logrus' },
        // { id: 43, selectionData: 'Rust' },
        // { id: 44, selectionData: 'Serde' },
        // { id: 45, selectionData: 'Tokio' },
        // { id: 46, selectionData: 'Actix-web' },
        // { id: 47, selectionData: 'Rocket' },
        // { id: 48, selectionData: 'Diesel' },
        // { id: 49, selectionData: 'C++' },
        // { id: 50, selectionData: 'Boost' },
        // { id: 51, selectionData: 'OpenCV' },
        // { id: 52, selectionData: 'Poco' },
        // { id: 53, selectionData: 'Qt' },
        // { id: 54, selectionData: 'GLM' },
        // { id: 55, selectionData: 'Swift' },
        // { id: 56, selectionData: 'Alamofire' },
        // { id: 57, selectionData: 'SwiftyJSON' },
        // { id: 58, selectionData: 'Kingfisher' },
        // { id: 59, selectionData: 'SnapKit' },
        // { id: 60, selectionData: 'RxSwift' },
        // { id: 61, selectionData: 'Kotlin' },
        // { id: 62, selectionData: 'Kotlinx Coroutines' },
        // { id: 63, selectionData: 'Ktor' },
        // { id: 64, selectionData: 'Room' },
        // { id: 65, selectionData: 'Retrofit' },
        // { id: 66, selectionData: 'Gson' },
        // { id: 67, selectionData: 'TypeScript' },
        // { id: 68, selectionData: 'TypeORM' },
        // { id: 69, selectionData: 'RxJS' },
        // { id: 70, selectionData: 'NestJS' },
        // { id: 71, selectionData: 'Jest' },
        // { id: 72, selectionData: 'ts-node' }
    ];
    
    export default SelectionDatas;
    