name: GitHub Auto Commit Bot

on:
  schedule:
    - cron: "0 0,4,8,12,16 * * *"  # Run at 00:00, 04:00, 08:00, 12:00, and 16:00 (5 times a day)
  workflow_dispatch:  # Allow manual trigger

jobs:
  run-commit-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Set maximum runtime to 30 minutes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Create a dummy commit
        run: |
          echo "Commit made on $(date)" >> commit.log
          git config --global user.name "your-github-username"
          git config --global user.email "your-email@example.com"
          git add commit.log
          git commit -m "Auto commit on $(date)"
          git push
