name: Auto Commit Every Hour

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allow manual trigger too

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Make changes
        run: |
          # Example: update a timestamp file
          echo "Last update: $(date)" > last_update.txt

      - name: Commit and push
        run: |
          git add .
          git commit -m "Auto commit at $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }} HEAD:main
